name: Common CI

on:
  pull_request:
    paths-ignore: # keep in sync with zeebe-ci.yml trigger
      - '.ci/docker/test/*'
      - '.github/actions/**'
      - '.github/workflows/zeebe-*'
      - 'Dockerfile'
      - 'bom/*'
      - 'build-tools/**'
      - 'clients/**'
      - 'dist/**'
      - 'parent/*'
      - 'pom.xml'
      - 'zeebe/**'

jobs:
  test-summary:
    # Dummy job used for pull requests that do not trigger zeebe-ci
    # This name is hard-coded in the branch rules; remember to update that if this name changes
    name: Test summary
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
