name: Operate merge queue CI

on:
  merge_group: { }
  pull_request: { }
  workflow_dispatch: { }

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref == 'refs/heads/main' && github.sha || format('{0}-{1}', github.workflow, github.ref) }}

jobs:
  run-build:
    name: run-build
    uses: ./.github/workflows/operate-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }} # head_ref = branch name on PR, ref_name = `main` or `stable/**`
      pushDocker: false

  operate-ci-test-summary:
    # Used by the merge queue to check all jobs.
    # New test jobs must be added to the `needs` lists!
    # This name is hard-coded in the branch rules; remember to update that if this name changes
    name: Operate CI test summary
    if: always()
    runs-on: ubuntu-latest
    needs:
      - run-build
    steps:
      - run: exit ${{ ((contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) && 1) || 0 }}
