---
name: Renovate lint
on:
  pull_request:
    paths:
      - '.github/workflows/renovatelint.yml'
      - '**/renovate.json'
      - '**/renovate.json5'

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref == 'refs/heads/main' && github.sha || format('{0}-{1}', github.workflow, github.ref) }}

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: renovate-config-validator --strict
