name: Tasklist Update Visual Regression Snapshots

on:
  pull_request:
    types: [labeled, synchronize]

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ github.ref == 'refs/heads/main' && github.sha || format('{0}-{1}', github.workflow, github.ref) }}

jobs:
  update-snapshots:
    if: github.event.pull_request.state != 'closed' && (github.event.label.name == 'update-snapshots' || contains( github.event.pull_request.labels.*.name, 'update-snapshots'))
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.3
      options: --user 1001:1000

    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: tasklist/client/yarn.lock
      - name: Install node dependencies
        working-directory: ./tasklist/client
        run: yarn
      - name: Build frontend
        working-directory: ./tasklist/client
        run: yarn build:visual-regression
      - name: Start server
        working-directory: ./tasklist/client
        run: yarn start:visual-regression &
      - name: Update snapshots
        working-directory: ./tasklist/client
        run: yarn playwright e2e/visual --update-snapshots
      - name: Commit screenshots
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: updated snapshots"
          file_pattern: "tasklist/client/**/*.png"
